version: "3.9"
services:
  db:
    image: postgres:16
    container_name: books_api_db
    environment:
      POSTGRES_DB: books_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
